-- ============ CREATION DES CLEFS PRIMAIRES

-- Il est important d'avoir un nom de contrainte pour que JPA reconnaisse les sequences
ALTER TABLE "YUCCA"."PROGRAMME"	ADD CONSTRAINT "PK_PROGRAMME" PRIMARY KEY ("ID");
ALTER TABLE "YUCCA"."CORRECTION" ADD CONSTRAINT "PK_CORRECTION" PRIMARY KEY ("ID");
ALTER TABLE "YUCCA"."VERSION" ADD CONSTRAINT "PK_VERSION" PRIMARY KEY ("ID");
ALTER TABLE "YUCCA"."REPERTOIRE" ADD CONSTRAINT "PK_REPERTOIRE" PRIMARY KEY ("ID");
ALTER TABLE "YUCCA"."DOMAINE" ADD CONSTRAINT "PK_DOMAINE" PRIMARY KEY ("ID");
ALTER TABLE "YUCCA"."SOUS_DOMAINE" ADD CONSTRAINT "PK_SOUS_DOMAINE" PRIMARY KEY ("ID");

