-- ============ CREATION DES CLEFS ETRANGES 

ALTER TABLE "YUCCA"."LIEN_CORRECTION_PROGRAMME" ADD CONSTRAINT "FK_CORRECTION" FOREIGN KEY ("ID_CORRECTION")
	REFERENCES "YUCCA"."CORRECTION"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

ALTER TABLE "YUCCA"."LIEN_CORRECTION_PROGRAMME" ADD CONSTRAINT "FK_PROGRAMME" FOREIGN KEY ("ID_PROGRAMME")
	REFERENCES "YUCCA"."PROGRAMME"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;
	
ALTER TABLE "YUCCA"."LIEN_CORRECTION_VERSION" ADD CONSTRAINT "FK_CORRECTION" FOREIGN KEY ("ID_CORRECTION")
	REFERENCES "YUCCA"."CORRECTION"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION ;

ALTER TABLE "YUCCA"."LIEN_CORRECTION_VERSION" ADD CONSTRAINT "FK_VERSION" FOREIGN KEY ("ID_VERSION")
	REFERENCES "YUCCA"."VERSION"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION ;


-- FK lies a PROGRAMME

ALTER TABLE "YUCCA"."PROGRAMME" ADD CONSTRAINT "FK_PROGRAMME_REPERTOIRE" FOREIGN KEY ("ID_REPERTOIRE")
	REFERENCES "YUCCA"."REPERTOIRE"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION ;	

ALTER TABLE "YUCCA"."PROGRAMME" ADD CONSTRAINT "FK_PROGRAMME_DOMAINE" FOREIGN KEY ("ID_DOMAINE")
	REFERENCES "YUCCA"."DOMAINE"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION ;	

ALTER TABLE "YUCCA"."PROGRAMME" ADD CONSTRAINT "FK_PROGRAMME_SOUS_DOMAINE" FOREIGN KEY ("ID_SOUS_DOMAINE")
	REFERENCES "YUCCA"."SOUS_DOMAINE"
		("ID")
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION ;	