-- ============ Pas d'ENUM en DB2 : CREATION CONTRAINTES CHECK

ALTER TABLE YUCCA.CORRECTION ADD CONSTRAINT CHECK_ETAT_CORRECTION CHECK (ETAT IN ('C','F','O','T'));
ALTER TABLE YUCCA.PROGRAMME ADD CONSTRAINT CHECK_TEMPORAIRE_PROGRAMME CHECK (TEMPORAIRE IN ('O','N'));
ALTER TABLE YUCCA.VERSION ADD CONSTRAINT CHECK_ETAT_VERSION CHECK (ETAT IN ('A','I', 'F'));