-- Table Version

INSERT INTO VERSION(LIBELLE, ETAT, CREATED_AT) VALUES
	('VERSION TEST 1', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 2', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 3', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 4', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 5', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 6', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 7', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 8', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 9', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 10', 'I', CAST(CURRENT TIMESTAMP AS DATE));
	
-- Table Programme

INSERT INTO PROGRAMME(NOM, COMMENTAIRE, TEMPORAIRE, ID_DOMAINE, ID_DOSSIER, CREATED_AT, CUSER, UPDATED_AT, MUSER) VALUES
	('NOM 1', 'COMMENTAIRE 1', 'N', 1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 2', 'COMMENTAIRE 2', 'O', 1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 3', 'COMMENTAIRE 3', 'O',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 4', 'COMMENTAIRE 4', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 5', 'COMMENTAIRE 5', 'O',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 6', 'COMMENTAIRE 6', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 7', 'COMMENTAIRE 7', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 8', 'COMMENTAIRE 8', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 9', 'COMMENTAIRE 9', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('NOM 10', 'COMMENTAIRE 10', 'N',1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV');

-- Table Correction
	
INSERT INTO CORRECTION(TITRE, PROBLEME, SOLUTION, COMMENTAIRE, ETAT, CREATED_AT, CUSER, UPDATED_AT, MUSER) VALUES
	('TITRE 1', 'PROBLEME 1', 'SOLUTION 1', 'COMMENTAIRE 1', 'O',  CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 2', 'PROBLEME 2', 'SOLUTION 2', 'COMMENTAIRE 2', 'O',  CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 3', 'PROBLEME 3', 'SOLUTION 3', 'COMMENTAIRE 3', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 4', 'PROBLEME 4', 'SOLUTION 4', 'COMMENTAIRE 4', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 5', 'PROBLEME 5', 'SOLUTION 5', 'COMMENTAIRE 5', 'O', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 6', 'PROBLEME 6', 'SOLUTION 6', 'COMMENTAIRE 6', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 7', 'PROBLEME 7', 'SOLUTION 7', 'COMMENTAIRE 7', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 8', 'PROBLEME 8', 'SOLUTION 8', 'COMMENTAIRE 8', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 9', 'PROBLEME 9', 'SOLUTION 9', 'COMMENTAIRE 9', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV'),
	('TITRE 10', 'PROBLEME 10', 'SOLUTION 10', 'COMMENTAIRE 10', 'O',   CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV', CAST(CURRENT TIMESTAMP AS DATE), 'YUCCA_DEV');
	
	
-- CORRECTION PROGRAMME

INSERT INTO LIEN_CORRECTION_PROGRAMME(ID_CORRECTION, ID_PROGRAMME) VALUES
	(1, 1),
	(1, 2), 
	(1, 3),
	(1, 4),
	(2, 2),
	(2, 1),
	(4, 5),
	(4, 6),
	(4, 7),
	(5, 8),
	(5, 10),
	(6, 10),
	(10, 9),
	(10, 10);
	
-- CORRECTION VERSION

INSERT INTO LIEN_CORRECTION_VERSION(ID_CORRECTION, ID_VERSION) VALUES
	(1, 2), 
	(1, 3),
	(1, 4),
	(2, 2),
	(2, 1),
	(5, 10),
	(6, 10),
	(10, 9),
	(10, 10);
	