INSERT INTO VERSION(LIBELLE, ETAT, CREATED_AT) VALUES
	('VERSION TEST 1', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 2', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 3', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 4', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 5', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 6', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 7', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 8', 'I', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 9', 'A', CAST(CURRENT TIMESTAMP AS DATE)),
	('VERSION TEST 10', 'I', CAST(CURRENT TIMESTAMP AS DATE));