-- Table Version

INSERT INTO VERSION(LIBELLE, ETAT, CREATED_AT, CUSER, UPDATED_AT, MUSER) VALUES
	('VERSION TEST 1', 'A', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 2', 'I', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 3', 'A', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 4', 'I', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 5', 'A', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 6', 'I', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 7', 'A', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 8', 'I', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 9', 'A', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('VERSION TEST 10', 'I', CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV');
	
-- Table Programme

INSERT INTO PROGRAMME(ID_PROGRAMME, NOM, COMMENTAIRE, TEMPORAIRE, ID_REPERTOIRE, ID_DOMAINE, ID_SOUS_DOMAINE, CREATED_AT, CUSER, UPDATED_AT, MUSER) VALUES
	(1, 'NOM 1', 'COMMENTAIRE 1', 'N', 1, 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(2, 'NOM 2', 'COMMENTAIRE 2', 'O', 5, 8, 21,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(3, 'NOM 3', 'COMMENTAIRE 3', 'O', 10, 3, 2,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(4, 'NOM 4', 'COMMENTAIRE 4', 'N', 5, 6, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(5, 'NOM 5', 'COMMENTAIRE 5', 'O', 2, 1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(6, 'NOM 6', 'COMMENTAIRE 6', 'N', 3, 1, 4, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(7, 'NOM 7', 'COMMENTAIRE 7', 'N', 4, 2, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(8, 'NOM 8', 'COMMENTAIRE 8', 'N', 8, 3, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(9, 'NOM 9', 'COMMENTAIRE 9', 'N', 1, 3, 8,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(10, 'NOM 10', 'COMMENTAIRE 10', 'N', 4, 8, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(11, 'NOM 11', 'COMMENTAIRE 11', 'N', 1, 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(12, 'NOM 12', 'COMMENTAIRE 12', 'O', 5, 8, 21,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(13, 'NOM 13', 'COMMENTAIRE 13', 'O', 10, 3, 2,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(14, 'NOM 14', 'COMMENTAIRE 14', 'N', 5, 6, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(15, 'NOM 15', 'COMMENTAIRE 15', 'O', 2, 1, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(16, 'NOM 16', 'COMMENTAIRE 16', 'N', 3, 1, 4, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(17, 'NOM 17', 'COMMENTAIRE 17', 'N', 4, 2, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(18, 'NOM 18', 'COMMENTAIRE 18', 'N', 8, 3, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(19, 'NOM 19', 'COMMENTAIRE 19', 'N', 1, 3, 8,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	(20, 'NOM 20', 'COMMENTAIRE 20', 'N', 4, 8, 1,  CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV');

-- Table Correction
	
INSERT INTO CORRECTION(TITRE, PROBLEME, SOLUTION, COMMENTAIRE, ETAT, ID_APPLICATION, ID_RESPONSABLE, CREATED_AT, CUSER, UPDATED_AT, MUSER) VALUES
	('TITRE 1', 'PROBLEME 1', 'SOLUTION 1', 'COMMENTAIRE 1', 'O',  1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 2', 'PROBLEME 2', 'SOLUTION 2', 'COMMENTAIRE 2', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 3', 'PROBLEME 3', 'SOLUTION 3', 'COMMENTAIRE 3', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 4', 'PROBLEME 4', 'SOLUTION 4', 'COMMENTAIRE 4', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 5', 'PROBLEME 5', 'SOLUTION 5', 'COMMENTAIRE 5', 'O',  1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 6', 'PROBLEME 6', 'SOLUTION 6', 'COMMENTAIRE 6', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 7', 'PROBLEME 7', 'SOLUTION 7', 'COMMENTAIRE 7', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 8', 'PROBLEME 8', 'SOLUTION 8', 'COMMENTAIRE 8', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 9', 'PROBLEME 9', 'SOLUTION 9', 'COMMENTAIRE 9', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV'),
	('TITRE 10', 'PROBLEME 10', 'SOLUTION 10', 'COMMENTAIRE 10', 'O', 1, 1, CURRENT TIMESTAMP, 'YUCCA_DEV', CURRENT TIMESTAMP, 'YUCCA_DEV');
	
	
-- CORRECTION PROGRAMME

INSERT INTO LIEN_CORRECTION_PROGRAMME(ID_CORRECTION, ID_PROGRAMME) VALUES
	(1, 2), 
	(1, 3),
	(1, 4),
	(2, 2),
	(2, 1),
	(5, 10),
	(6, 10),
	(10, 9),
	(10, 10);
	
-- CORRECTION VERSION

INSERT INTO LIEN_CORRECTION_VERSION(ID_CORRECTION, ID_VERSION) VALUES
	(1, 2), 
	(1, 3),
	(1, 4),
	(2, 2),
	(2, 1),
	(5, 10),
	(6, 10),
	(10, 9),
	(10, 10);
	