--=========================================== Création des bufferpools

CREATE BUFFERPOOL "YUCCA_BIS_DATA_BP"
IMMEDIATE
SIZE 100000 AUTOMATIC
PAGESIZE 16K;


--=========================================== Création des tablespaces

CREATE LARGE TABLESPACE TS_YUCCA_BIS_DATA
PAGESIZE 16K
 MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
BUFFERPOOL YUCCA_BIS_DATA_BP
NO FILE SYSTEM CACHING
DROPPED TABLE RECOVERY ON;
