--=========================================== Création de la table Programme

CREATE TABLE "YUCCA"."PROGRAMME"  (
		  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 2147483647
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ),
		  "NOM" VARCHAR(50) NOT NULL ,
		  "COMMENTAIRE" VARCHAR(200),  -- Anciennement COMM
		  "TEMPORAIRE" CHAR(1) WITH DEFAULT 'N' ,  -- Anciennement TEMPO
		  "ID_REPERTOIRE" SMALLINT, -- Anciennement IDDOSSIER, doit etre NOT NULL mais a la migration il y a des données NULL
		  "ID_DOMAINE" SMALLINT NOT NULL WITH DEFAULT 1 , -- Anciennement TAPSER smallint de la Table PROTAP		  
		  "ID_SOUS_DOMAINE" SMALLINT NOT NULL ,  -- Anciennement PROGDOM smallint
		  "CREATED_AT" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP ,
		  "CUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA' , 
		  "UPDATED_AT" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP ,
		  "MUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA'
		 )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";
		 
-- IL FAUT AJOUTER LES DEUX FK POUR LES DEUX TABLES MANQUANTES

--=========================================== Création de la table Correction

CREATE TABLE "YUCCA"."CORRECTION"  (
		  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER) ,   -- Nouvelle CP/PK pour historisation  
		  "TITRE" VARCHAR(100), -- Anciennement CORFIC char(100)
		  "CODE_PROBLEME" VARCHAR(50), -- Anciennement SIGTOUL dans la table SIGNALEMENT
		  "PROBLEME" CLOB(2000), --Anciennement CORPB
		  "SOLUTION" CLOB(3000), --Anciennement CORSOL
		  "COMMENTAIRE" CLOB(2000) ,  --Anciennement CORMOD
		  "ETAT" CHAR(1) WITH DEFAULT 'O' ,
		  "ID_DOMAINE" SMALLINT NOT NULL ,  -- Anciennement TAPSER
		  "ID_AUTEUR" SMALLINT , -- Anciennement RESPSER
		  "CREATED_AT" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP , -- Anciennement CORDAT
		  "CUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA' , 
		  "UPDATED_AT" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP ,
		  "MUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA'
		  )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";

--=========================================== Création de la table de Liaision Anciennement CORPROG qui lie Correction et Programmes

CREATE TABLE "YUCCA"."LIEN_CORRECTION_PROGRAMME"  (
		  "ID_CORRECTION" INTEGER NOT NULL , -- Anciennement CORSER 
		  "ID_PROGRAMME" INTEGER NOT NULL  -- Anciennement PROGSER   
		  ) 
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";
		 
--=========================================== Création de la table Version

CREATE TABLE "YUCCA"."VERSION"  (
		  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,
		  "LIBELLE" VARCHAR(30), -- Anciennement VERLIB
		  "ACTIVE" SMALLINT NOT NULL, -- ATTENTION : Colonne temporaire pour migration des donnees
		  "ETAT" CHAR(1) NOT NULL WITH DEFAULT 'A' ,		  
		  "CREATED_AT" TIMESTAMP NOT NULL WITH DEFAULT CURRENT TIMESTAMP ,  -- Anciennement CREATION
		  "CUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA' , 
		  "UPDATED_AT" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP ,
		  "MUSER" VARCHAR(10) NOT NULL WITH DEFAULT 'YUCCA'
		  )		  
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";


--=========================================== Création de la table de Liaision anciennement CORVER qui lie Correction et Version

CREATE TABLE "YUCCA"."LIEN_CORRECTION_VERSION"  (
		  "ID_CORRECTION" INTEGER NOT NULL , -- Anciennement CORSER 
		  "ID_VERSION" INTEGER NOT NULL  -- Anciennement VERID 
		  )   
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";

--=========================================== Création de la table REPERTOIRE (anciennement TDOSSIER)
		 
CREATE TABLE "YUCCA"."REPERTOIRE"  (
		  "ID" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 32767  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,   -- Anciennement DOSID smallint
		  "CHEMIN" VARCHAR(100) , --Anciennement DOSLIL varchar(100)
		  "RACCOURCI_UNIX" VARCHAR(20), --Anciennement DOSNOM varchar(20)
          "VISIBLE" CHAR(1) NOT NULL WITH DEFAULT 1 -- Anciennement DOSLA CHAR(1)
		  )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";

--=========================================== Création de la table DOMAINE (anciennement APPLICATION)
		 
CREATE TABLE "YUCCA"."DOMAINE"  (
		  "ID" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 32767  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,   -- Anciennement TAPSER smallint	  
		  "LIBELLE_COURT" CHAR(10) NOT NULL, -- Anciennement TAPAPP char(10)
		  "LIBELLE_LONG" CHAR(60) NOT NULL, --Anciennement TAPLIB
		  "VISIBLE" CHAR(1) NOT NULL WITH DEFAULT 1 -- Anciennement VISIBLE INTEGER
		  )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";

--=========================================== Création de la table SOUS_DOMAINE (anciennement DOMAINE)
		 
CREATE TABLE "YUCCA"."SOUS_DOMAINE"  (
		  "ID" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 32767  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,   -- Anciennement DOMSER smallint		  
		  "LIBELLE_COURT" VARCHAR(10) NOT NULL, -- Anciennement DOMCOU char(10)
		  "LIBELLE_LONG" VARCHAR(60) NOT NULL, --Anciennement DOMLIB
		  "VISIBLE" CHAR(1) NOT NULL WITH DEFAULT 1 -- Anciennement VISIBLE INTEGER		  
		  )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";

--=========================================== Création de la table AUTEUR (anciennement TRESP)

CREATE TABLE "YUCCA"."AUTEUR"  (
		  "ID" SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
		    START WITH 1  
		    INCREMENT BY 1  
		    MINVALUE 1  
		    MAXVALUE 32767  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,   -- Anciennement  RESPSER smallint		  
		  "ALIAS" VARCHAR(3) NOT NULL, -- Anciennement  RESPLIC 
		  "NOM" VARCHAR(30) NOT NULL, --Anciennement RESPLIL
		  "ACTIF" CHAR(1) NOT NULL WITH DEFAULT 'O' -- Anciennement RESPLA		  
		  )
		 IN "TS_YUCCA_BIS_DATA" INDEX IN "TS_YUCCA_BIS_INDEX";
