-- ATTENTION il faut avoir migré les données avant de lancer ce script
-- Migration des donnees de la colonne ACTIVE vers la colonne ETAT (leur equivalent)

UPDATE "YUCCA".VERSION
SET ETAT = 'I'
WHERE ACTIVE = 0;

-- Suppression de la colonne ACTIVE

ALTER TABLE "YUCCA".VERSION DROP COLUMN "ACTIVE";

CALL SYSPROC.ADMIN_CMD ('REORG TABLE "YUCCA".VERSION');


-- SUPRRESSION des données incohérentes identifiées durant les precedantes migrations

-- SELECT * 
-- FROM YUCCA.LIEN_CORRECTION_VERSION
-- WHERE ID_VERSION NOT IN (SELECT ID FROM YUCCA.VERSION) 

DELETE FROM YUCCA.LIEN_CORRECTION_VERSION WHERE ID_VERSION=653;


UPDATE "YUCCA".PROGRAMME
SET TEMPORAIRE='N'
WHERE TEMPORAIRE IS NULL;


-- MISE A JOUR DES DONNES PAR RAPPORT A L'US DATE DE CREATION DE L'ANCIEN YUCCA
-- SI CETTE US EST IMPLEMENTEE, IL N'Y AURA PLUS BESOIN DE FAIRE CETTE OPERATION

UPDATE "YUCCA".VERSION
SET CREATED_AT=TIMESTAMP('2019-01-01-00.00.00.000000') + ID SECONDS;

CALL SYSPROC.ADMIN_CMD ('REORG TABLE "YUCCA".VERSION');
