-- PREMIERE VERSION : on ne connait pas le nom des sequences

CREATE PROCEDURE "YUCCA".MAJ_SEQUENCE_PROGRAMME(OUT retour VARCHAR(150))
LANGUAGE SQL
BEGIN
	DECLARE maxi INTEGER;
	DECLARE txt VARCHAR(150);
	SELECT MAX(ID) INTO maxi FROM YUCCA.PROGRAMME;
	SET txt = CONCAT('ALTER TABLE YUCCA.PROGRAMME ALTER COLUMN "ID" RESTART WITH ', maxi+1);
	SET retour = txt;
	EXECUTE IMMEDIATE txt;
END;

CREATE PROCEDURE "YUCCA".MAJ_SEQUENCE_CORRECTION(OUT retour VARCHAR(150))
LANGUAGE SQL
BEGIN
	DECLARE maxi INTEGER;
	DECLARE txt VARCHAR(150);
	SELECT MAX(ID) INTO maxi FROM YUCCA.CORRECTION;
	SET txt = CONCAT('ALTER TABLE YUCCA.CORRECTION ALTER COLUMN "ID" RESTART WITH ', maxi+1);
	SET retour = txt;
	EXECUTE IMMEDIATE txt;
END;

CREATE PROCEDURE "YUCCA".MAJ_SEQUENCE_VERSION(OUT retour VARCHAR(150))
LANGUAGE SQL
BEGIN
	DECLARE maxi INTEGER;
	DECLARE txt VARCHAR(150);
	SELECT MAX(ID) INTO maxi FROM YUCCA.VERSION;
	SET txt = CONCAT('ALTER TABLE YUCCA.VERSION ALTER COLUMN "ID" RESTART WITH ', maxi+1);
	SET retour = txt;
	EXECUTE IMMEDIATE txt;
END;

CALL YUCCA.MAJ_SEQUENCE_PROGRAMME(?);
CALL YUCCA.MAJ_SEQUENCE_CORRECTION(?);
CALL YUCCA.MAJ_SEQUENCE_VERSION(?);